INSERT INTO datasource (id, name, source_identifier, type)
VALUES (nextVal('datasource_id_seq'), 'Barnegat Light, NJ', '08005', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Bodega Bay, CA', '94922', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Ilwaco, WA', '98624', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Harbor, OR', '97415', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Charleston, OR', '97420', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Bandon, OR', '97411', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Depoe Bay, OR', '97341', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Sausalito, CA', '94965', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Westport, WA', '98595', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Hatteras, NC', '27943', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Samoa, CA', '95564', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Newburyport, MA', '01950', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Morro Bay, CA', '93442', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Fort Bragg, CA', '95437', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Ocracoke, NC', '27960', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Nags Head, NC', '27959', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'La Push, WA', '98350', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Gold Beach, OR', '97444', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Florence, OR', '97439', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Garibaldi, OR', '97118', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Winchester Bay, OR', '97467', 'WEATHER'),
       (nextVal('datasource_id_seq'), 'Newport, OR', '97365', 'WEATHER');

-- Insert into join table
INSERT INTO station_datasource (station_id, datasource_id, display_order)
VALUES ((SELECT id FROM station WHERE city = 'Barnegat Light' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '08005' LIMIT 1), 4),
       ((SELECT id FROM station WHERE city = 'Bodega Bay' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '94922' LIMIT 1), 3),
       ((SELECT id FROM station WHERE city = 'Ilwaco' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '98624' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Harbor' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97415' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Charleston' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97420' LIMIT 1), 6),
       ((SELECT id FROM station WHERE city = 'Bandon' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97411' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Depoe Bay' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97341' LIMIT 1), 4),
       ((SELECT id FROM station WHERE city = 'Sausalito' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '94965' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Westport' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '98595' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Hatteras' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '27943' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Samoa' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '95564' LIMIT 1), 4),
       ((SELECT id FROM station WHERE city = 'Newburyport' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '01950' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Morro Bay' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '93442' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Fort Bragg' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '95437' LIMIT 1), 4),
       ((SELECT id FROM station WHERE city = 'Ocracoke' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '27960' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Nags Head' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '27959' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'La Push' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '98350' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Gold Beach' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97444' LIMIT 1), 4),
       ((SELECT id FROM station WHERE city = 'Florence' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97439' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Garibaldi' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97118' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Winchester Bay' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97467' LIMIT 1), 5),
       ((SELECT id FROM station WHERE city = 'Newport' LIMIT 1),
        (SELECT id FROM datasource WHERE source_identifier = '97365' LIMIT 1), 4);

