CREATE TABLE datasources
(
    id                SERIAL PRIMARY KEY,
    name              VARCHAR(50),
    source_identifier VARCHAR(50),
    type              VARCHAR(50),
    unique (source_identifier, type)
);

CREATE TABLE stations_datasources
(
    station_id    INT NOT NULL,
    datasource_id INT NOT NULL,
    "order"       INT NOT NULL,
    PRIMARY KEY (station_id, datasource_id),
    CONSTRAINT fk_station FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE,
    CONSTRAINT fk_datasources FOREIGN KEY (datasource_id) REFERENCES datasources (id) ON DELETE CASCADE,
    constraint unique_station_datasource_order unique (station_id, "order")
);

-- Populating datasources table with unique source_identifier and type combinations
INSERT INTO datasources (source_identifier, type, name)
VALUES ('44091', 'WAVE', '44091 - BARNEGAT'),
       ('8533615', 'TIDE', 'BARNEGAT INLET'),
       ('ACT4001', 'CURRENT', 'BARNEGAT INLET'),
       ('FZUS51.KPHI', 'FORECAST', 'FZUS51.KPHI'),
       ('46214', 'WAVE', '46214 - POINT REYES'),
       ('9415625', 'TIDE', 'BODEGA HARBOR ENTRANCE'),
       ('FZUS56.KMTR', 'FORECAST', 'FZUS56.KMTR'),
       ('46243', 'WAVE', '46243 - CLATSOP SPIT'),
       ('46029', 'WIND', 'COLUMBIA RIVER BAR'),
       ('9440574', 'TIDE', 'COLUMBIA RIVER ENTRANCE'),
       ('PCT1121', 'CURRENT', 'CLATSOP SPIT'),
       ('FZUS56.KPQR', 'FORECAST', 'FZUS56.KPQR'),
       ('46027', 'WAVE', '46027 - ST GEORGES'),
       ('46027', 'WIND', '46027 - ST GEORGES'),
       ('9430104', 'TIDE', 'CHETCO COVE'),
       ('46015', 'WAVE', '46015 - PORT ORFORD'),
       ('FZUS56.KMFR', 'FORECAST', 'FZUS56.KMFR'),
       ('46229', 'WAVE', '46229 - UMPQUA OFFSHORE'),
       ('CHAO3', 'WIND', 'CHARLESTON'),
       ('9432780', 'TIDE', 'CHARLESTON'),
       ('PCT1061', 'CURRENT', 'COOS BAY ENTRANCE'),
       ('PORO3', 'WIND', 'PORO3 - PORT ORFORD'),
       ('9432373', 'TIDE', 'COQUILLE RIVER'),
       ('PCT1056', 'CURRENT', 'COQUILLE RIVER ENTRANCE'),
       ('46050', 'WAVE', '46050 - STONEWALL BANK'),
       ('46050', 'WIND', '46050 - STONEWALL BANK'),
       ('9435827', 'TIDE', 'DEPOE BAY'),
       ('46026', 'WAVE', '46026 - SAN FRANCISCO'),
       ('46026', 'WIND', '46026 - SAN FRANCISCO'),
       ('9414906', 'TIDE', 'POINT BONITA'),
       ('PCT0181', 'CURRENT', 'POINT BONITA LT'),
       ('46211', 'WAVE', '46211 - GRAYS HARBOR'),
       ('WPTW1', 'WIND', 'WESTPORT'),
       ('9441102', 'TIDE', 'POINT CHEHALIS'),
       ('PCT1291', 'CURRENT', 'GRAYS HARBOR ENTRANCE'),
       ('FZUS56.KSEW', 'FORECAST', 'FZUS56.KSEW'),
       ('41120', 'WAVE', '41120 - CAPE HATTERAS EAST'),
       ('41025', 'WIND', 'DIAMOND SHOALS'),
       ('TEC2791', 'TIDE', 'HATTERAS INLET'),
       ('ACT6286', 'CURRENT', 'HATTERAS INLET'),
       ('FZUS52.KMHX', 'FORECAST', 'FZUS52.KMHX'),
       ('46244', 'WAVE', '46244 - HUMBOLDT BAY'),
       ('46022', 'WIND', 'EEL RIVER'),
       ('9418767', 'TIDE', 'HUMBOLDT BAY NORTH SPIT'),
       ('FZUS56.KEKA', 'FORECAST', 'FZUS56.KEKA'),
       ('44098', 'WAVE', '44098 - JEFFREYS LEDGE'),
       ('IOSN3', 'WIND', 'ISLE OF SHOALS'),
       ('8440452', 'TIDE', 'MERRIMACK RIVER ENTRANCE'),
       ('ACT0816', 'CURRENT', 'MERRIMACK RIVER ENTRANCE'),
       ('FZUS51.KBOX', 'FORECAST', 'FZUS51.KBOX'),
       ('46215', 'WAVE', '46215 - DIABLO CANYON'),
       ('46011', 'WAVE', '46011 - SANTA MARIA'),
       ('46011', 'WIND', '46011 - SANTA MARIA'),
       ('9412110', 'TIDE', 'PORT SAN LUIS'),
       ('FZUS56.KLOX', 'FORECAST', 'FZUS56.KLOX'),
       ('46014', 'WAVE', '46014 - PT ARENA'),
       ('46014', 'WIND', '46014 - PT ARENA'),
       ('9417426', 'TIDE', 'NOYO HARBOR'),
       ('TEC2793', 'TIDE', 'OCRACOKE INLET'),
       ('ACT6296', 'CURRENT', 'OCRACOKE INLET'),
       ('44095', 'WAVE', '44095 - OREGON INLET'),
       ('ORIN7', 'WIND', 'OREGON INLET MARINA'),
       ('8652678', 'TIDE', 'OREGON INLET'),
       ('ACT6271', 'CURRENT', 'OREGON INLET'),
       ('46041', 'WAVE', '46041 - CAPE ELIZABETH'),
       ('LAPW1', 'WIND', 'LA PUSH'),
       ('9442388', 'TIDE', 'QUILLAYUTE RIVER'),
       ('PCT1321', 'CURRENT', 'QUILLAYUTE RIVER ENTRANCE'),
       ('9431011', 'TIDE', 'ROGUE RIVER'),
       ('46098', 'WIND', 'WALDPORT OFFSHORE'),
       ('9434132', 'TIDE', 'SIUSLAW RIVER ENTRANCE'),
       ('46248', 'WAVE', '46248 - ASTORIA CANYON'),
       ('9437585', 'TIDE', 'NORTH JETTY'),
       ('PCT1096', 'CURRENT', 'TILLAMOOK BAY ENTRANCE'),
       ('9433445', 'TIDE', 'UMPQUA RIVER ENTRANCE'),
       ('PCT1066', 'CURRENT', 'UMPQUA RIVER ENTRANCE'),
       ('9435380', 'TIDE', 'SOUTHBEACH'),
       ('PCT1076', 'CURRENT', 'YAQUINA BAY ENTRANCE');

-- Populating station_datasources join table with sequential order
INSERT INTO stations_datasources (station_id, datasource_id, "order")
VALUES (1, (SELECT id FROM datasources WHERE source_identifier = '44091' AND type = 'WAVE'), 1),
       (1, (SELECT id FROM datasources WHERE source_identifier = '8533615' AND type = 'TIDE'), 2),
       (1, (SELECT id FROM datasources WHERE source_identifier = 'ACT4001' AND type = 'CURRENT'), 3),
       (1, (SELECT id FROM datasources WHERE source_identifier = 'FZUS51.KPHI' AND type = 'FORECAST'), 4),
       (2, (SELECT id FROM datasources WHERE source_identifier = '46214' AND type = 'WAVE'), 1),
       (2, (SELECT id FROM datasources WHERE source_identifier = '9415625' AND type = 'TIDE'), 2),
       (2, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMTR' AND type = 'FORECAST'), 3),
       (3, (SELECT id FROM datasources WHERE source_identifier = '46243' AND type = 'WAVE'), 1),
       (3, (SELECT id FROM datasources WHERE source_identifier = '46029' AND type = 'WIND'), 2),
       (3, (SELECT id FROM datasources WHERE source_identifier = '9440574' AND type = 'TIDE'), 3),
       (3, (SELECT id FROM datasources WHERE source_identifier = 'PCT1121' AND type = 'CURRENT'), 4),
       (3, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KPQR' AND type = 'FORECAST'), 5),
       (4, (SELECT id FROM datasources WHERE source_identifier = '46027' AND type = 'WAVE'), 1),
       (4, (SELECT id FROM datasources WHERE source_identifier = '46027' AND type = 'WIND'), 2),
       (4, (SELECT id FROM datasources WHERE source_identifier = '9430104' AND type = 'TIDE'), 3),
       (4, (SELECT id FROM datasources WHERE source_identifier = '46015' AND type = 'WAVE'), 4),
       (4, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 5),
       (5, (SELECT id FROM datasources WHERE source_identifier = '46229' AND type = 'WAVE'), 1),
       (5, (SELECT id FROM datasources WHERE source_identifier = 'CHAO3' AND type = 'WIND'), 2),
       (5, (SELECT id FROM datasources WHERE source_identifier = '9432780' AND type = 'TIDE'), 3),
       (5, (SELECT id FROM datasources WHERE source_identifier = 'PCT1061' AND type = 'CURRENT'), 4),
       (5, (SELECT id FROM datasources WHERE source_identifier = '46015' AND type = 'WAVE'), 5),
       (5, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 6),
       (6, (SELECT id FROM datasources WHERE source_identifier = '46015' AND type = 'WAVE'), 1),
       (6, (SELECT id FROM datasources WHERE source_identifier = 'PORO3' AND type = 'WIND'), 2),
       (6, (SELECT id FROM datasources WHERE source_identifier = '9432373' AND type = 'TIDE'), 3),
       (6, (SELECT id FROM datasources WHERE source_identifier = 'PCT1056' AND type = 'CURRENT'), 4),
       (6, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 5),
       (7, (SELECT id FROM datasources WHERE source_identifier = '46050' AND type = 'WAVE'), 1),
       (7, (SELECT id FROM datasources WHERE source_identifier = '46050' AND type = 'WIND'), 2),
       (7, (SELECT id FROM datasources WHERE source_identifier = '9435827' AND type = 'TIDE'), 3),
       (7, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KPQR' AND type = 'FORECAST'), 4),
       (8, (SELECT id FROM datasources WHERE source_identifier = '46026' AND type = 'WAVE'), 1),
       (8, (SELECT id FROM datasources WHERE source_identifier = '46026' AND type = 'WIND'), 2),
       (8, (SELECT id FROM datasources WHERE source_identifier = '9414906' AND type = 'TIDE'), 3),
       (8, (SELECT id FROM datasources WHERE source_identifier = 'PCT0181' AND type = 'CURRENT'), 4),
       (8, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMTR' AND type = 'FORECAST'), 5),
       (9, (SELECT id FROM datasources WHERE source_identifier = '46211' AND type = 'WAVE'), 1),
       (9, (SELECT id FROM datasources WHERE source_identifier = 'WPTW1' AND type = 'WIND'), 2),
       (9, (SELECT id FROM datasources WHERE source_identifier = '9441102' AND type = 'TIDE'), 3),
       (9, (SELECT id FROM datasources WHERE source_identifier = 'PCT1291' AND type = 'CURRENT'), 4),
       (9, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KSEW' AND type = 'FORECAST'), 5),
       (10, (SELECT id FROM datasources WHERE source_identifier = '41120' AND type = 'WAVE'), 1),
       (10, (SELECT id FROM datasources WHERE source_identifier = '41025' AND type = 'WIND'), 2),
       (10, (SELECT id FROM datasources WHERE source_identifier = 'TEC2791' AND type = 'TIDE'), 3),
       (10, (SELECT id FROM datasources WHERE source_identifier = 'ACT6286' AND type = 'CURRENT'), 4),
       (10, (SELECT id FROM datasources WHERE source_identifier = 'FZUS52.KMHX' AND type = 'FORECAST'), 5),
       (11, (SELECT id FROM datasources WHERE source_identifier = '46244' AND type = 'WAVE'), 1),
       (11, (SELECT id FROM datasources WHERE source_identifier = '46022' AND type = 'WIND'), 2),
       (11, (SELECT id FROM datasources WHERE source_identifier = '9418767' AND type = 'TIDE'), 3),
       (11, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KEKA' AND type = 'FORECAST'), 4),
       (12, (SELECT id FROM datasources WHERE source_identifier = '44098' AND type = 'WAVE'), 1),
       (12, (SELECT id FROM datasources WHERE source_identifier = 'IOSN3' AND type = 'WIND'), 2),
       (12, (SELECT id FROM datasources WHERE source_identifier = '8440452' AND type = 'TIDE'), 3),
       (12, (SELECT id FROM datasources WHERE source_identifier = 'ACT0816' AND type = 'CURRENT'), 4),
       (12, (SELECT id FROM datasources WHERE source_identifier = 'FZUS51.KBOX' AND type = 'FORECAST'), 5),
       (13, (SELECT id FROM datasources WHERE source_identifier = '46215' AND type = 'WAVE'), 1),
       (13, (SELECT id FROM datasources WHERE source_identifier = '46011' AND type = 'WIND'), 2),
       (13, (SELECT id FROM datasources WHERE source_identifier = '9412110' AND type = 'TIDE'), 3),
       (13, (SELECT id FROM datasources WHERE source_identifier = '46011' AND type = 'WAVE'), 4),
       (13, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KLOX' AND type = 'FORECAST'), 5),
       (14, (SELECT id FROM datasources WHERE source_identifier = '46014' AND type = 'WAVE'), 1),
       (14, (SELECT id FROM datasources WHERE source_identifier = '46014' AND type = 'WIND'), 2),
       (14, (SELECT id FROM datasources WHERE source_identifier = '9417426' AND type = 'TIDE'), 3),
       (14, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KEKA' AND type = 'FORECAST'), 4),
       (15, (SELECT id FROM datasources WHERE source_identifier = '41120' AND type = 'WAVE'), 1),
       (15, (SELECT id FROM datasources WHERE source_identifier = '41025' AND type = 'WIND'), 2),
       (15, (SELECT id FROM datasources WHERE source_identifier = 'TEC2793' AND type = 'TIDE'), 3),
       (15, (SELECT id FROM datasources WHERE source_identifier = 'ACT6296' AND type = 'CURRENT'), 4),
       (15, (SELECT id FROM datasources WHERE source_identifier = 'FZUS52.KMHX' AND type = 'FORECAST'), 5),
       (16, (SELECT id FROM datasources WHERE source_identifier = '44095' AND type = 'WAVE'), 1),
       (16, (SELECT id FROM datasources WHERE source_identifier = 'ORIN7' AND type = 'WIND'), 2),
       (16, (SELECT id FROM datasources WHERE source_identifier = '8652678' AND type = 'TIDE'), 3),
       (16, (SELECT id FROM datasources WHERE source_identifier = 'ACT6271' AND type = 'CURRENT'), 4),
       (16, (SELECT id FROM datasources WHERE source_identifier = 'FZUS52.KMHX' AND type = 'FORECAST'), 5),
       (17, (SELECT id FROM datasources WHERE source_identifier = '46041' AND type = 'WAVE'), 1),
       (17, (SELECT id FROM datasources WHERE source_identifier = 'LAPW1' AND type = 'WIND'), 2),
       (17, (SELECT id FROM datasources WHERE source_identifier = '9442388' AND type = 'TIDE'), 3),
       (17, (SELECT id FROM datasources WHERE source_identifier = 'PCT1321' AND type = 'CURRENT'), 4),
       (17, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KSEW' AND type = 'FORECAST'), 5),
       (18, (SELECT id FROM datasources WHERE source_identifier = '46015' AND type = 'WAVE'), 1),
       (18, (SELECT id FROM datasources WHERE source_identifier = 'PORO3' AND type = 'WIND'), 2),
       (18, (SELECT id FROM datasources WHERE source_identifier = '9431011' AND type = 'TIDE'), 3),
       (18, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 4),
       (19, (SELECT id FROM datasources WHERE source_identifier = '46229' AND type = 'WAVE'), 1),
       (19, (SELECT id FROM datasources WHERE source_identifier = '46098' AND type = 'WIND'), 2),
       (19, (SELECT id FROM datasources WHERE source_identifier = '9434132' AND type = 'TIDE'), 3),
       (19, (SELECT id FROM datasources WHERE source_identifier = '46050' AND type = 'WAVE'), 4),
       (19, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 5),
       (20, (SELECT id FROM datasources WHERE source_identifier = '46248' AND type = 'WAVE'), 1),
       (20, (SELECT id FROM datasources WHERE source_identifier = '9437585' AND type = 'TIDE'), 2),
       (20, (SELECT id FROM datasources WHERE source_identifier = 'PCT1096' AND type = 'CURRENT'), 3),
       (20, (SELECT id FROM datasources WHERE source_identifier = '46050' AND type = 'WAVE'), 4),
       (20, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KPQR' AND type = 'FORECAST'), 5),
       (21, (SELECT id FROM datasources WHERE source_identifier = '46229' AND type = 'WAVE'), 1),
       (21, (SELECT id FROM datasources WHERE source_identifier = '46098' AND type = 'WIND'), 2),
       (21, (SELECT id FROM datasources WHERE source_identifier = '9433445' AND type = 'TIDE'), 3),
       (21, (SELECT id FROM datasources WHERE source_identifier = 'PCT1066' AND type = 'CURRENT'), 4),
       (21, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KMFR' AND type = 'FORECAST'), 5),
       (22, (SELECT id FROM datasources WHERE source_identifier = '46050' AND type = 'WAVE'), 1),
       (22, (SELECT id FROM datasources WHERE source_identifier = '9435380' AND type = 'TIDE'), 2),
       (22, (SELECT id FROM datasources WHERE source_identifier = 'PCT1076' AND type = 'CURRENT'), 3),
       (22, (SELECT id FROM datasources WHERE source_identifier = 'FZUS56.KPQR' AND type = 'FORECAST'), 4);
