  version: '3.8'
  services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
#    keycloak:
#      image: quay.io/keycloak/keycloak:25.0.2
#      environment:
#        KEYCLOAK_ADMIN:
#        KEYCLOAK_ADMIN_PASSWORD:
#      ports:
#        - "8080:8080"
#      depends_on:
#        - postgres
  volumes:
    pg_data:
      driver: local