spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
security:
    jwt:
        secret: ${JWT_SECRET}
        expiration: 3600000